### ISSUE TITLE
Lettuce connect the cluster to refresh the topology graph and the number of connections keeps growing

### ISSUE THREAD

**Issue by mindong789** [lettuce-io/lettuce-core#1369]
#### Current Behavior

<details>
<summary>Stack trace</summary>

```java
// your stack trace here;
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
// your code here;
```

</details>

#### Environment

- Lettuce version(s): [e.g. 5.0.0.RELEASE, 4.2.2.Final]
- Redis version: [e.g. 4.0.9]

**Comment by mindong789** [comment]
connectCluster([RedisURI [host='192.168.20.145', port=6479]])
Resolved SocketAddress 192.168.20.145:6480 using for Cluster node d3492ca2cae9454f936074eca2fab7f1dcf471c5
Connecting to Redis at 192.168.20.145:6480
[channel=0x49ef0501, [id: 0xd2934f57] (inactive), chid=0x1b] channelRegistered()
[channel=0x49ef0501, /192.168.23.199:54192 -> /192.168.20.145:6480, chid=0x1b] channelActive()
[channel=0x49ef0501, /192.168.23.199:54192 -> /192.168.20.145:6480, epid=0x1b] activateEndpointAndExecuteBufferedCommands 0 command(s) buffered
[channel=0x49ef0501, /192.168.23.199:54192 -> /192.168.20.145:6480, epid=0x1b] activating endpoint
[channel=0x49ef0501, /192.168.23.199:54192 -> /192.168.20.145:6480, epid=0x1b] flushCommands()
[channel=0x49ef0501, /192.168.23.199:54192 -> /192.168.20.145:6480, epid=0x1b] flushCommands() Flushing 0 commands
[channel=0x49ef0501, /192.168.23.199:54192 -> /192.168.20.145:6480, last known addr=/192.168.20.145:6480] channelActive()
[channel=0x49ef0501, /192.168.23.199:54192 -> /192.168.20.145:6480, chid=0x1b] channelActive() done
Connecting to Redis at 192.168.20.145:6480: Success
dispatching command SubscriptionCommand [type=COMMAND, output=ArrayOutput [output=[], error='null'], commandType=io.lettuce.core.protocol.Command]
[channel=0x49ef0501, /192.168.23.199:54192 -> /192.168.20.145:6480, epid=0x1b] write() writeAndFlush command ClusterCommand [command=SubscriptionCommand [type=COMMAND, output=ArrayOutput [output=[], error='null'], commandType=io.lettuce.core.protocol.Command], redirections=0, maxRedirections=3]
[channel=0x49ef0501, /192.168.23.199:54192 -> /192.168.20.145:6480, chid=0x1b] write(ctx, ClusterCommand [command=SubscriptionCommand [type=COMMAND, output=ArrayOutput [output=[], error='null'], commandType=io.lettuce.core.protocol.Command], redirections=0, maxRedirections=3], promise)
[channel=0x49ef0501, /192.168.23.199:54192 -> /192.168.20.145:6480] writing command ClusterCommand [command=SubscriptionCommand [type=COMMAND, output=ArrayOutput [output=[], error='null'], commandType=io.lettuce.core.protocol.Command], redirections=0, maxRedirections=3]
[channel=0x49ef0501, /192.168.23.199:54192 -> /192.168.20.145:6480, epid=0x1b] write() done
[channel=0x49ef0501, /192.168.23.199:54192 -> /192.168.20.145:6480, last known addr=/192.168.20.145:6480] userEventTriggered(ctx, io.lettuce.core.ConnectionEvents$Activated@55889f42)
[channel=0x49ef0501, /192.168.23.199:54192 -> /192.168.20.145:6480, chid=0x1b] Received: 1024 bytes, 1 commands in the stack
[channel=0x49ef0501, /192.168.23.199:54192 -> /192.168.20.145:6480, chid=0x1b] Stack contains: 1 commands
Decode ClusterCommand [command=SubscriptionCommand [type=COMMAND, output=ArrayOutput [output=[], error='null'], commandType=io.lettuce.core.protocol.Command], redirections=0, maxRedirections=3]
Decoded ClusterCommand [command=SubscriptionCommand [type=COMMAND, output=ArrayOutput [output=[lrem, 4, [write], 1], error='null'], commandType=io.lettuce.core.protocol.Command], redirections=0, maxRedirections=3], empty stack: false
[channel=0x49ef0501, /192.168.23.199:54192 -> /192.168.20.145:6480, chid=0x1b] Received: 9139 bytes, 1 commands in the stack
[channel=0x49ef0501, /192.168.23.199:54192 -> /192.168.20.145:6480, chid=0x1b] Stack contains: 1 commands
Decode ClusterCommand [command=SubscriptionCommand [type=COMMAND, output=ArrayOutput [output=[lrem, 4, [write], 1], error='null'], commandType=io.lettuce.core.protocol.Command], redirections=0, maxRedirections=3]
Decoded ClusterCommand [command=SubscriptionCommand [type=COMMAND, output=ArrayOutput [output=[[sort, -2, [write, denyoom, movablekeys], 1, 1, 1], [sinterstore, -3, [write, denyoom], 1, -1, 1], [decrby, 3, [write, denyoom, fast], 1, 1, 1], [memory, -2, [readonly], 0, 0, 0], [zremrangebylex, 4, [write], 1, 1, 1], [exec, 1, [noscript, skip_monitor], 0, 0, 0], [latency, -2, [admin, noscript, loading, stale], 0, 0, 0], [zinterstore, -4, [write, denyoom, movablekeys], 0, 0, 0], [cluster, -2, [admin], 0, 0, 0], [hincrby, 4, [write, denyoom, fast], 1, 1, 1], [geodist, -4, [readonly], 1, 1, 1], [time, 1, [random, fast], 0, 0, 0], [mget, -2, [readonly, fast], 1, -1, 1], [migrate, -6, [write, movablekeys], 0, 0, 0], [rename, 3, [write], 1, 2, 1], [srandmember, -2, [readonly, random], 1, 1, 1], [discard, 1, [noscript, fast], 0, 0, 0], [lrem, 4, [write], 1, 1, 1], [scan, -2, [readonly, random], 0, 0, 0], [setrange, 4, [write, denyoom], 1, 1, 1], [unlink, -2, [write, fast], 1, -1, 1], [sdiff, -2, [readonly, sort_for_script], 1, -1, 1], [select, 2, [loading, fast], 0, 0, 0], [hlen, 2, [readonly, fast], 1, 1, 1], [unsubscribe, -1, [pubsub, noscript, loading, stale], 0, 0, 0], [role, 1, [noscript, loading, stale], 0, 0, 0], [swapdb, 3, [write, fast], 0, 0, 0], [rpop, 2, [write, fast], 1, 1, 1], [keys, 2, [readonly, sort_for_script], 0, 0, 0], [bgrewriteaof, 1, [admin], 0, 0, 0], [lastsave, 1, [random, fast], 0, 0, 0], [zscore, 3, [readonly, fast], 1, 1, 1], [getset, 3, [write, denyoom], 1, 1, 1], [ttl, 2, [readonly, fast], 1, 1, 1], [strlen, 2, [readonly, fast], 1, 1, 1], [pfmerge, -2, [write, denyoom], 1, -1, 1], [lpushx, -3, [write, denyoom, fast], 1, 1, 1], [eval, -3, [noscript, movablekeys], 0, 0, 0], [monitor, 1, [admin, noscript], 0, 0, 0], [incrby, 3, [write, denyoom, fast], 1, 1, 1], [brpoplpush, 4, [write, denyoom, noscript], 1, 2, 1], [publish, 3, [pubsub, loading, stale, fast], 0, 0, 0], [hstrlen, 3, [readonly, fast], 1, 1, 1], [hkeys, 2, [readonly, sort_for_script], 1, 1, 1], [hincrbyfloat, 4, [write, denyoom, fast], 1, 1, 1], [rpushx, -3, [write, denyoom, fast], 1, 1, 1], [move, 3, [write, fast], 1, 1, 1], [geohash, -2, [readonly], 1, 1, 1], [ping, -1, [stale, fast], 0, 0, 0], [smembers, 2, [readonly, sort_for_script], 1, 1, 1], [pfcount, -2, [readonly], 1, -1, 1], [post, -1, [loading, stale], 0, 0, 0], [hgetall, 2, [readonly], 1, 1, 1], [pexpire, 3, [write, fast], 1, 1, 1], [slaveof, 3, [admin, noscript, stale], 0, 0, 0], [sunionstore, -3, [write, denyoom], 1, -1, 1], [substr, 4, [readonly], 1, 1, 1], [zrank, 3, [readonly, fast], 1, 1, 1], [setnx, 3, [write, denyoom, fast], 1, 1, 1], [sscan, -3, [readonly, random], 1, 1, 1], [readwrite, 1, [fast], 0, 0, 0], [auth, 2, [noscript, loading, stale, fast], 0, 0, 0], [zscan, -3, [readonly, random], 1, 1, 1], [zadd, -4, [write, denyoom, fast], 1, 1, 1], [blpop, -3, [write, noscript], 1, -2, 1], [sismember, 3, [readonly, fast], 1, 1, 1], [info, -1, [loading, stale], 0, 0, 0], [setbit, 4, [write, denyoom], 1, 1, 1], [zincrby, 4, [write, denyoom, fast], 1, 1, 1], [lindex, 3, [readonly], 1, 1, 1], [lset, 4, [write, denyoom], 1, 1, 1], [asking, 1, [fast], 0, 0, 0], [getbit, 3, [readonly, fast], 1, 1, 1], [dbsize, 1, [readonly, fast], 0, 0, 0], [flushdb, -1, [write], 0, 0, 0], [rpoplpush, 3, [write, denyoom], 1, 2, 1], [sdiffstore, -3, [write, denyoom], 1, -1, 1], [shutdown, -1, [admin, loading, stale], 0, 0, 0], [sunion, -2, [readonly, sort_for_script], 1, -1, 1], [persist, 2, [write, fast], 1, 1, 1], [randomkey, 1, [readonly, random], 0, 0, 0], [linsert, 5, [write, denyoom], 1, 1, 1], [bitfield, -2, [write, denyoom], 1, 1, 1], [script, -2, [noscript], 0, 0, 0], [config, -2, [admin, loading, stale], 0, 0, 0], [expireat, 3, [write, fast], 1, 1, 1], [zrevrank, 3, [readonly, fast], 1, 1, 1], [debug, -1, [admin, noscript], 0, 0, 0], [hdel, -3, [write, fast], 1, 1, 1], [incr, 2, [write, denyoom, fast], 1, 1, 1], [lpop, 2, [write, fast], 1, 1, 1], [georadiusbymember, -5, [write, movablekeys], 1, 1, 1], [hget, 3, [readonly, fast], 1, 1, 1], [evalsha, -3, [noscript, movablekeys], 0, 0, 0], [geoadd, -5, [write, denyoom], 1, 1, 1], [readonly, 1, [fast], 0, 0, 0], [command, 0, [loading, stale], 0, 0, 0], [restore-asking, -4, [write, denyoom, asking], 1, 1, 1], [zrange, -4, [readonly], 1, 1, 1], [georadiusbymember_ro, -5, [readonly, movablekeys], 1, 1, 1], [zrangebyscore, -4, [readonly], 1, 1, 1], [echo, 2, [fast], 0, 0, 0], [get, 2, [readonly, fast], 1, 1, 1], [subscribe, -2, [pubsub, noscript, loading, stale], 0, 0, 0], [psetex, 4, [write, denyoom], 1, 1, 1], [smove, 4, [write, fast], 1, 2, 1], [pexpireat, 3, [write, fast], 1, 1, 1], [zremrangebyrank, 4, [write], 1, 1, 1], [zrevrangebyscore, -4, [readonly], 1, 1, 1], [sinter, -2, [readonly, sort_for_script], 1, -1, 1], [georadius, -6, [write, movablekeys], 1, 1, 1], [psubscribe, -2, [pubsub, noscript, loading, stale], 0, 0, 0], [hmget, -3, [readonly, fast], 1, 1, 1], [llen, 2, [readonly, fast], 1, 1, 1], [pttl, 2, [readonly, fast], 1, 1, 1], [expire, 3, [write, fast], 1, 1, 1], [replconf, -1, [admin, noscript, loading, stale], 0, 0, 0], [brpop, -3, [write, noscript], 1, -2, 1], [hexists, 3, [readonly, fast], 1, 1, 1], [lrange, 4, [readonly], 1, 1, 1], [georadius_ro, -6, [readonly, movablekeys], 1, 1, 1], [touch, -2, [readonly, fast], 1, 1, 1], [renamenx, 3, [write, fast], 1, 2, 1], [msetnx, -3, [write, denyoom], 1, -1, 2], [lpush, -3, [write, denyoom, fast], 1, 1, 1], [set, -3, [write, denyoom], 1, 1, 1], [spop, -2, [write, random, fast], 1, 1, 1], [rpush, -3, [write, denyoom, fast], 1, 1, 1], [hvals, 2, [readonly, sort_for_script], 1, 1, 1], [hscan, -3, [readonly, random], 1, 1, 1], [append, 3, [write, denyoom], 1, 1, 1], [bitop, -4, [write, denyoom], 2, -1, 1], [object, -2, [readonly], 2, 2, 2], [srem, -3, [write, fast], 1, 1, 1], [pfselftest, 1, [admin], 0, 0, 0], [del, -2, [write], 1, -1, 1], [multi, 1, [noscript, fast], 0, 0, 0], [pfadd, -2, [write, denyoom, fast], 1, 1, 1], [zunionstore, -4, [write, denyoom, movablekeys], 0, 0, 0], [bitpos, -3, [readonly], 1, 1, 1], [zlexcount, 4, [readonly, fast], 1, 1, 1], [ltrim, 4, [write], 1, 1, 1], [flushall, -1, [write], 0, 0, 0], [zcount, 4, [readonly, fast], 1, 1, 1], [wait, 3, [noscript], 0, 0, 0], [dump, 2, [readonly], 1, 1, 1], [psync, 3, [readonly, admin, noscript], 0, 0, 0], [zrem, -3, [write, fast], 1, 1, 1], [incrbyfloat, 3, [write, denyoom, fast], 1, 1, 1], [pfdebug, -3, [write], 0, 0, 0], [host:, -1, [loading, stale], 0, 0, 0], [slowlog, -2, [admin], 0, 0, 0], [scard, 2, [readonly, fast], 1, 1, 1], [zcard, 2, [readonly, fast], 1, 1, 1], [type, 2, [readonly, fast], 1, 1, 1], [restore, -4, [write, denyoom], 1, 1, 1], [unwatch, 1, [noscript, fast], 0, 0, 0], [setex, 4, [write, denyoom], 1, 1, 1], [bgsave, -1, [admin], 0, 0, 0], [hmset, -4, [write, denyoom, fast], 1, 1, 1], [client, -2, [admin, noscript], 0, 0, 0], [zremrangebyscore, 4, [write], 1, 1, 1], [punsubscribe, -1, [pubsub, noscript, loading, stale], 0, 0, 0], [zrevrangebylex, -4, [readonly], 1, 1, 1], [getrange, 4, [readonly], 1, 1, 1], [sadd, -3, [write, denyoom, fast], 1, 1, 1], [geopos, -2, [readonly], 1, 1, 1], [module, -2, [admin, noscript], 0, 0, 0], [bitcount, -2, [readonly], 1, 1, 1], [zrevrange, -4, [readonly], 1, 1, 1], [zrangebylex, -4, [readonly], 1, 1, 1], [sync, 1, [readonly, admin, noscript], 0, 0, 0], [hset, -4, [write, denyoom, fast], 1, 1, 1], [mset, -3, [write, denyoom], 1, -1, 2], [watch, -2, [noscript, fast], 1, -1, 1], [decr, 2, [write, denyoom, fast], 1, 1, 1], [pubsub, -2, [pubsub, random, loading, stale], 0, 0, 0], [hsetnx, 4, [write, denyoom, fast], 1, 1, 1], [exists, -2, [readonly, fast], 1, -1, 1], [save, 1, [admin, noscript], 0, 0, 0]], error='null'], commandType=io.lettuce.core.protocol.Command], redirections=0, maxRedirections=3], empty stack: true
dispatching command AsyncCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command]
getConnection(READ, 11510)
Resolved SocketAddress 192.168.20.145:6481 using for Cluster node at 192.168.20.145:6481
Connecting to Redis at 192.168.20.145:6481
[channel=0xe624dcc2, [id: 0x00d92ad7] (inactive), chid=0x1c] channelRegistered()
[channel=0xe624dcc2, /192.168.23.199:44606 -> /192.168.20.145:6481, chid=0x1c] channelActive()
[channel=0xe624dcc2, /192.168.23.199:44606 -> /192.168.20.145:6481, epid=0x1c] activateEndpointAndExecuteBufferedCommands 0 command(s) buffered
[channel=0xe624dcc2, /192.168.23.199:44606 -> /192.168.20.145:6481, epid=0x1c] activating endpoint
[channel=0xe624dcc2, /192.168.23.199:44606 -> /192.168.20.145:6481, epid=0x1c] flushCommands()
[channel=0xe624dcc2, /192.168.23.199:44606 -> /192.168.20.145:6481, epid=0x1c] flushCommands() Flushing 0 commands
[channel=0xe624dcc2, /192.168.23.199:44606 -> /192.168.20.145:6481, last known addr=/192.168.20.145:6481] channelActive()
[channel=0xe624dcc2, /192.168.23.199:44606 -> /192.168.20.145:6481, chid=0x1c] channelActive() done
Connecting to Redis at 192.168.20.145:6481: Success
[channel=0xe624dcc2, /192.168.23.199:44606 -> /192.168.20.145:6481, epid=0x1c] write() writeAndFlush command ClusterCommand [command=AsyncCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command], redirections=0, maxRedirections=3]
[channel=0xe624dcc2, /192.168.23.199:44606 -> /192.168.20.145:6481, chid=0x1c] write(ctx, ClusterCommand [command=AsyncCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command], redirections=0, maxRedirections=3], promise)
[channel=0xe624dcc2, /192.168.23.199:44606 -> /192.168.20.145:6481] writing command ClusterCommand [command=AsyncCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command], redirections=0, maxRedirections=3]
[channel=0xe624dcc2, /192.168.23.199:44606 -> /192.168.20.145:6481, epid=0x1c] write() done
[channel=0xe624dcc2, /192.168.23.199:44606 -> /192.168.20.145:6481, last known addr=/192.168.20.145:6481] userEventTriggered(ctx, io.lettuce.core.ConnectionEvents$Activated@7e532557)
[channel=0xe624dcc2, /192.168.23.199:44606 -> /192.168.20.145:6481, chid=0x1c] Received: 1024 bytes, 1 commands in the stack
[channel=0xe624dcc2, /192.168.23.199:44606 -> /192.168.20.145:6481, chid=0x1c] Stack contains: 1 commands
Decode ClusterCommand [command=AsyncCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command], redirections=0, maxRedirections=3]
Decoded ClusterCommand [command=AsyncCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command], redirections=0, maxRedirections=3], empty stack: false
[channel=0xe624dcc2, /192.168.23.199:44606 -> /192.168.20.145:6481, chid=0x1c] Received: 286 bytes, 1 commands in the stack
[channel=0xe624dcc2, /192.168.23.199:44606 -> /192.168.20.145:6481, chid=0x1c] Stack contains: 1 commands
Decode ClusterCommand [command=AsyncCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command], redirections=0, maxRedirections=3]
Decoded ClusterCommand [command=AsyncCommand [type=GET, output=ValueOutput [output=[B@17f66e6d, error='null'], commandType=io.lettuce.core.protocol.Command], redirections=0, maxRedirections=3], empty stack: true
connectCluster([RedisURI [host='192.168.20.145', port=6479]])
Resolved SocketAddress 192.168.20.145:6480 using for Cluster node d3492ca2cae9454f936074eca2fab7f1dcf471c5
Connecting to Redis at 192.168.20.145:6480
[channel=0x9e0ec83b, [id: 0x47ae246c] (inactive), chid=0x1d] channelRegistered()
[channel=0x9e0ec83b, /192.168.23.199:54196 -> /192.168.20.145:6480, chid=0x1d] channelActive()
[channel=0x9e0ec83b, /192.168.23.199:54196 -> /192.168.20.145:6480, epid=0x1d] activateEndpointAndExecuteBufferedCommands 0 command(s) buffered
[channel=0x9e0ec83b, /192.168.23.199:54196 -> /192.168.20.145:6480, epid=0x1d] activating endpoint
[channel=0x9e0ec83b, /192.168.23.199:54196 -> /192.168.20.145:6480, epid=0x1d] flushCommands()
[channel=0x9e0ec83b, /192.168.23.199:54196 -> /192.168.20.145:6480, epid=0x1d] flushCommands() Flushing 0 commands
[channel=0x9e0ec83b, /192.168.23.199:54196 -> /192.168.20.145:6480, last known addr=/192.168.20.145:6480] channelActive()
[channel=0x9e0ec83b, /192.168.23.199:54196 -> /192.168.20.145:6480, chid=0x1d] channelActive() done
Connecting to Redis at 192.168.20.145:6480: Success
dispatching command SubscriptionCommand [type=COMMAND, output=ArrayOutput [output=[], error='null'], commandType=io.lettuce.core.protocol.Command]
[channel=0x9e0ec83b, /192.168.23.199:54196 -> /192.168.20.145:6480, epid=0x1d] write() writeAndFlush command ClusterCommand [command=SubscriptionCommand [type=COMMAND, output=ArrayOutput [output=[], error='null'], commandType=io.lettuce.core.protocol.Command], redirections=0, maxRedirections=3]
[channel=0x9e0ec83b, /192.168.23.199:54196 -> /192.168.20.145:6480, chid=0x1d] write(ctx, ClusterCommand [command=SubscriptionCommand [type=COMMAND, output=ArrayOutput [output=[], error='null'], commandType=io.lettuce.core.protocol.Command], redirections=0, maxRedirections=3], promise)
[channel=0x9e0ec83b, /192.168.23.199:54196 -> /192.168.20.145:6480] writing command ClusterCommand [command=SubscriptionCommand [type=COMMAND, output=ArrayOutput [output=[], error='null'], commandType=io.lettuce.core.protocol.Command], redirections=0, maxRedirections=3]
[channel=0x9e0ec83b, /192.168.23.199:54196 -> /192.168.20.145:6480, epid=0x1d] write() done
[channel=0x9e0ec83b, /192.168.23.199:54196 -> /192.168.20.145:6480, last known addr=/192.168.20.145:6480] userEventTriggered(ctx, io.lettuce.core.ConnectionEvents$Activated@6c5bc316)
[channel=0x9e0ec83b, /192.168.23.199:54196 -> /192.168.20.145:6480, chid=0x1d] Received: 1024 bytes, 1 commands in the stack
[channel=0x9e0ec83b, /192.168.23.199:54196 -> /192.168.20.145:6480, chid=0x1d] Stack contains: 1 commands
Decode ClusterCommand [command=SubscriptionCommand [type=COMMAND, output=ArrayOutput [output=[], error='null'], commandType=io.lettuce.core.protocol.Command], redirections=0, maxRedirections=3]
Decoded ClusterCommand [command=SubscriptionCommand [type=COMMAND, output=ArrayOutput [output=[lrem, 4, [write], 1], error='null'], commandType=io.lettuce.core.protocol.Command], redirections=0, maxRedirections=3], empty stack: false
[channel=0x9e0ec83b, /192.168.23.199:54196 -> /192.168.20.145:6480, chid=0x1d] Received: 9139 bytes, 1 commands in the stack
[channel=0x9e0ec83b, /192.168.23.199:54196 -> /192.168.20.145:6480, chid=0x1d] Stack contains: 1 commands
Decode ClusterCommand [command=SubscriptionCommand [type=COMMAND, output=ArrayOutput [output=[lrem, 4, [write], 1], error='null'], commandType=io.lettuce.core.protocol.Command], redirections=0, maxRedirections=3]
Decoded ClusterCommand [command=SubscriptionCommand [type=COMMAND, output=ArrayOutput [output=[[sort, -2, [write, denyoom, movablekeys], 1, 1, 1], [sinterstore, -3, [write, denyoom], 1, -1, 1], [decrby, 3, [write, denyoom, fast], 1, 1, 1], [memory, -2, [readonly], 0, 0, 0], [zremrangebylex, 4, [write], 1, 1, 1], [exec, 1, [noscript, skip_monitor], 0, 0, 0], [latency, -2, [admin, noscript, loading, stale], 0, 0, 0], [zinterstore, -4, [write, denyoom, movablekeys], 0, 0, 0], [cluster, -2, [admin], 0, 0, 0], [hincrby, 4, [write, denyoom, fast], 1, 1, 1], [geodist, -4, [readonly], 1, 1, 1], [time, 1, [random, fast], 0, 0, 0], [mget, -2, [readonly, fast], 1, -1, 1], [migrate, -6, [write, movablekeys], 0, 0, 0], [rename, 3, [write], 1, 2, 1], [srandmember, -2, [readonly, random], 1, 1, 1], [discard, 1, [noscript, fast], 0, 0, 0], [lrem, 4, [write], 1, 1, 1], [scan, -2, [readonly, random], 0, 0, 0], [setrange, 4, [write, denyoom], 1, 1, 1], [unlink, -2, [write, fast], 1, -1, 1], [sdiff, -2, [readonly, sort_for_script], 1, -1, 1], [select, 2, [loading, fast], 0, 0, 0], [hlen, 2, [readonly, fast], 1, 1, 1], [unsubscribe, -1, [pubsub, noscript, loading, stale], 0, 0, 0], [role, 1, [noscript, loading, stale], 0, 0, 0], [swapdb, 3, [write, fast], 0, 0, 0], [rpop, 2, [write, fast], 1, 1, 1], [keys, 2, [readonly, sort_for_script], 0, 0, 0], [bgrewriteaof, 1, [admin], 0, 0, 0], [lastsave, 1, [random, fast], 0, 0, 0], [zscore, 3, [readonly, fast], 1, 1, 1], [getset, 3, [write, denyoom], 1, 1, 1], [ttl, 2, [readonly, fast], 1, 1, 1], [strlen, 2, [readonly, fast], 1, 1, 1], [pfmerge, -2, [write, denyoom], 1, -1, 1], [lpushx, -3, [write, denyoom, fast], 1, 1, 1], [eval, -3, [noscript, movablekeys], 0, 0, 0], [monitor, 1, [admin, noscript], 0, 0, 0], [incrby, 3, [write, denyoom, fast], 1, 1, 1], [brpoplpush, 4, [write, denyoom, noscript], 1, 2, 1], [publish, 3, [pubsub, loading, stale, fast], 0, 0, 0], [hstrlen, 3, [readonly, fast], 1, 1, 1], [hkeys, 2, [readonly, sort_for_script], 1, 1, 1], [hincrbyfloat, 4, [write, denyoom, fast], 1, 1, 1], [rpushx, -3, [write, denyoom, fast], 1, 1, 1], [move, 3, [write, fast], 1, 1, 1], [geohash, -2, [readonly], 1, 1, 1], [ping, -1, [stale, fast], 0, 0, 0], [smembers, 2, [readonly, sort_for_script], 1, 1, 1], [pfcount, -2, [readonly], 1, -1, 1], [post, -1, [loading, stale], 0, 0, 0], [hgetall, 2, [readonly], 1, 1, 1], [pexpire, 3, [write, fast], 1, 1, 1], [slaveof, 3, [admin, noscript, stale], 0, 0, 0], [sunionstore, -3, [write, denyoom], 1, -1, 1], [substr, 4, [readonly], 1, 1, 1], [zrank, 3, [readonly, fast], 1, 1, 1], [setnx, 3, [write, denyoom, fast], 1, 1, 1], [sscan, -3, [readonly, random], 1, 1, 1], [readwrite, 1, [fast], 0, 0, 0], [auth, 2, [noscript, loading, stale, fast], 0, 0, 0], [zscan, -3, [readonly, random], 1, 1, 1], [zadd, -4, [write, denyoom, fast], 1, 1, 1], [blpop, -3, [write, noscript], 1, -2, 1], [sismember, 3, [readonly, fast], 1, 1, 1], [info, -1, [loading, stale], 0, 0, 0], [setbit, 4, [write, denyoom], 1, 1, 1], [zincrby, 4, [write, denyoom, fast], 1, 1, 1], [lindex, 3, [readonly], 1, 1, 1], [lset, 4, [write, denyoom], 1, 1, 1], [asking, 1, [fast], 0, 0, 0], [getbit, 3, [readonly, fast], 1, 1, 1], [dbsize, 1, [readonly, fast], 0, 0, 0], [flushdb, -1, [write], 0, 0, 0], [rpoplpush, 3, [write, denyoom], 1, 2, 1], [sdiffstore, -3, [write, denyoom], 1, -1, 1], [shutdown, -1, [admin, loading, stale], 0, 0, 0], [sunion, -2, [readonly, sort_for_script], 1, -1, 1], [persist, 2, [write, fast], 1, 1, 1], [randomkey, 1, [readonly, random], 0, 0, 0], [linsert, 5, [write, denyoom], 1, 1, 1], [bitfield, -2, [write, denyoom], 1, 1, 1], [script, -2, [noscript], 0, 0, 0], [config, -2, [admin, loading, stale], 0, 0, 0], [expireat, 3, [write, fast], 1, 1, 1], [zrevrank, 3, [readonly, fast], 1, 1, 1], [debug, -1, [admin, noscript], 0, 0, 0], [hdel, -3, [write, fast], 1, 1, 1], [incr, 2, [write, denyoom, fast], 1, 1, 1], [lpop, 2, [write, fast], 1, 1, 1], [georadiusbymember, -5, [write, movablekeys], 1, 1, 1], [hget, 3, [readonly, fast], 1, 1, 1], [evalsha, -3, [noscript, movablekeys], 0, 0, 0], [geoadd, -5, [write, denyoom], 1, 1, 1], [readonly, 1, [fast], 0, 0, 0], [command, 0, [loading, stale], 0, 0, 0], [restore-asking, -4, [write, denyoom, asking], 1, 1, 1], [zrange, -4, [readonly], 1, 1, 1], [georadiusbymember_ro, -5, [readonly, movablekeys], 1, 1, 1], [zrangebyscore, -4, [readonly], 1, 1, 1], [echo, 2, [fast], 0, 0, 0], [get, 2, [readonly, fast], 1, 1, 1], [subscribe, -2, [pubsub, noscript, loading, stale], 0, 0, 0], [psetex, 4, [write, denyoom], 1, 1, 1], [smove, 4, [write, fast], 1, 2, 1], [pexpireat, 3, [write, fast], 1, 1, 1], [zremrangebyrank, 4, [write], 1, 1, 1], [zrevrangebyscore, -4, [readonly], 1, 1, 1], [sinter, -2, [readonly, sort_for_script], 1, -1, 1], [georadius, -6, [write, movablekeys], 1, 1, 1], [psubscribe, -2, [pubsub, noscript, loading, stale], 0, 0, 0], [hmget, -3, [readonly, fast], 1, 1, 1], [llen, 2, [readonly, fast], 1, 1, 1], [pttl, 2, [readonly, fast], 1, 1, 1], [expire, 3, [write, fast], 1, 1, 1], [replconf, -1, [admin, noscript, loading, stale], 0, 0, 0], [brpop, -3, [write, noscript], 1, -2, 1], [hexists, 3, [readonly, fast], 1, 1, 1], [lrange, 4, [readonly], 1, 1, 1], [georadius_ro, -6, [readonly, movablekeys], 1, 1, 1], [touch, -2, [readonly, fast], 1, 1, 1], [renamenx, 3, [write, fast], 1, 2, 1], [msetnx, -3, [write, denyoom], 1, -1, 2], [lpush, -3, [write, denyoom, fast], 1, 1, 1], [set, -3, [write, denyoom], 1, 1, 1], [spop, -2, [write, random, fast], 1, 1, 1], [rpush, -3, [write, denyoom, fast], 1, 1, 1], [hvals, 2, [readonly, sort_for_script], 1, 1, 1], [hscan, -3, [readonly, random], 1, 1, 1], [append, 3, [write, denyoom], 1, 1, 1], [bitop, -4, [write, denyoom], 2, -1, 1], [object, -2, [readonly], 2, 2, 2], [srem, -3, [write, fast], 1, 1, 1], [pfselftest, 1, [admin], 0, 0, 0], [del, -2, [write], 1, -1, 1], [multi, 1, [noscript, fast], 0, 0, 0], [pfadd, -2, [write, denyoom, fast], 1, 1, 1], [zunionstore, -4, [write, denyoom, movablekeys], 0, 0, 0], [bitpos, -3, [readonly], 1, 1, 1], [zlexcount, 4, [readonly, fast], 1, 1, 1], [ltrim, 4, [write], 1, 1, 1], [flushall, -1, [write], 0, 0, 0], [zcount, 4, [readonly, fast], 1, 1, 1], [wait, 3, [noscript], 0, 0, 0], [dump, 2, [readonly], 1, 1, 1], [psync, 3, [readonly, admin, noscript], 0, 0, 0], [zrem, -3, [write, fast], 1, 1, 1], [incrbyfloat, 3, [write, denyoom, fast], 1, 1, 1], [pfdebug, -3, [write], 0, 0, 0], [host:, -1, [loading, stale], 0, 0, 0], [slowlog, -2, [admin], 0, 0, 0], [scard, 2, [readonly, fast], 1, 1, 1], [zcard, 2, [readonly, fast], 1, 1, 1], [type, 2, [readonly, fast], 1, 1, 1], [restore, -4, [write, denyoom], 1, 1, 1], [unwatch, 1, [noscript, fast], 0, 0, 0], [setex, 4, [write, denyoom], 1, 1, 1], [bgsave, -1, [admin], 0, 0, 0], [hmset, -4, [write, denyoom, fast], 1, 1, 1], [client, -2, [admin, noscript], 0, 0, 0], [zremrangebyscore, 4, [write], 1, 1, 1], [punsubscribe, -1, [pubsub, noscript, loading, stale], 0, 0, 0], [zrevrangebylex, -4, [readonly], 1, 1, 1], [getrange, 4, [readonly], 1, 1, 1], [sadd, -3, [write, denyoom, fast], 1, 1, 1], [geopos, -2, [readonly], 1, 1, 1], [module, -2, [admin, noscript], 0, 0, 0], [bitcount, -2, [readonly], 1, 1, 1], [zrevrange, -4, [readonly], 1, 1, 1], [zrangebylex, -4, [readonly], 1, 1, 1], [sync, 1, [readonly, admin, noscript], 0, 0, 0], [hset, -4, [write, denyoom, fast], 1, 1, 1], [mset, -3, [write, denyoom], 1, -1, 2], [watch, -2, [noscript, fast], 1, -1, 1], [decr, 2, [write, denyoom, fast], 1, 1, 1], [pubsub, -2, [pubsub, random, loading, stale], 0, 0, 0], [hsetnx, 4, [write, denyoom, fast], 1, 1, 1], [exists, -2, [readonly, fast], 1, -1, 1], [save, 1, [admin, noscript], 0, 0, 0]], error='null'], commandType=io.lettuce.core.protocol.Command], redirections=0, maxRedirections=3], empty stack: true
dispatching command AsyncCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command]
getConnection(READ, 3177)
Resolved SocketAddress 192.168.20.145:6479 using for Cluster node at 192.168.20.145:6479
Connecting to Redis at 192.168.20.145:6479
[channel=0xa975eabe, [id: 0x2b329a47] (inactive), chid=0x1e] channelRegistered()
[channel=0xa975eabe, /192.168.23.199:20040 -> /192.168.20.145:6479, chid=0x1e] channelActive()
[channel=0xa975eabe, /192.168.23.199:20040 -> /192.168.20.145:6479, epid=0x1e] activateEndpointAndExecuteBufferedCommands 0 command(s) buffered
[channel=0xa975eabe, /192.168.23.199:20040 -> /192.168.20.145:6479, epid=0x1e] activating endpoint
[channel=0xa975eabe, /192.168.23.199:20040 -> /192.168.20.145:6479, epid=0x1e] flushCommands()
[channel=0xa975eabe, /192.168.23.199:20040 -> /192.168.20.145:6479, epid=0x1e] flushCommands() Flushing 0 commands
[channel=0xa975eabe, /192.168.23.199:20040 -> /192.168.20.145:6479, last known addr=/192.168.20.145:6479] channelActive()
[channel=0xa975eabe, /192.168.23.199:20040 -> /192.168.20.145:6479, chid=0x1e] channelActive() done
Connecting to Redis at 192.168.20.145:6479: Success
[channel=0xa975eabe, /192.168.23.199:20040 -> /192.168.20.145:6479, epid=0x1e] write() writeAndFlush command ClusterCommand [command=AsyncCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command], redirections=0, maxRedirections=3]
[channel=0xa975eabe, /192.168.23.199:20040 -> /192.168.20.145:6479, chid=0x1e] write(ctx, ClusterCommand [command=AsyncCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command], redirections=0, maxRedirections=3], promise)
[channel=0xa975eabe, /192.168.23.199:20040 -> /192.168.20.145:6479] writing command ClusterCommand [command=AsyncCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command], redirections=0, maxRedirections=3]
[channel=0xa975eabe, /192.168.23.199:20040 -> /192.168.20.145:6479, epid=0x1e] write() done
[channel=0xa975eabe, /192.168.23.199:20040 -> /192.168.20.145:6479, last known addr=/192.168.20.145:6479] userEventTriggered(ctx, io.lettuce.core.ConnectionEvents$Activated@d3017f6)
[channel=0xa975eabe, /192.168.23.199:20040 -> /192.168.20.145:6479, chid=0x1e] Received: 741 bytes, 1 commands in the stack
[channel=0xa975eabe, /192.168.23.199:20040 -> /192.168.20.145:6479, chid=0x1e] Stack contains: 1 commands
Decode ClusterCommand [command=AsyncCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command], redirections=0, maxRedirections=3]
Decoded ClusterCommand [command=AsyncCommand [type=GET, output=ValueOutput [output=[B@12b3372f, error='null'], commandType=io.lettuce.core.protocol.Command], redirections=0, maxRedirections=3], empty stack: true

**Comment by mindong789** [comment]
connected_clients:51
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0
127.0.0.1:6479> info Clients
# Clients
connected_clients:54
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0

**Comment by mp911de** [comment]
Can you check whether the same issue persists with Lettuce 6? We have a similar ticket at #1342.

**Comment by mindong789** [comment]
I am using 5.3.1.release.
Let me try Lettuce 6

**Comment by mp911de** [comment]
Closing this ticket as duplicate of #1342, we will continue on the other ticket.
